### ISSUE TITLE
Support the `width` and `height` attributes

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#152]
It's currently not possible to change the initial width and height, using HTML attributes:
`<mapml-viewer width="500" height="500">`

**Comment by prushforth** [comment]
Is that ok or not ok?  I think this should be done through CSS anyway, right?

**Comment by Malvoz** [comment]
It should be doable at least per the MapML spec:

> The `map` element supports the `width` and `height` dimension attributes. [HTML]

CSS always takes precedence over the attributes though.

I don't feel strongly about having the polyfill conform to the spec in this matter, authors will likely use CSS most of the time, but a native element would almost be guaranteed to support the `width` and `height` attributes, as does video, iframe, canvas, img and svg.

We can talk about why these attributes exist in HTML, and how they may or may not make sense in the context of a custom element, it's just that I had made an assumption that they were going to be supported.

**Comment by erictheise** [comment]
`width` and `height` really don't do anything? Why are they in the spec and examples?

**Comment by prushforth** [comment]
@erictheise 

> a native element would almost be guaranteed to support the width and height attributes, as does video, iframe, canvas, img and svg.

This is why.  Originally, the custom element only supported width and height, and especially because you have to have a height for Leaflet to work, and I wasn't sure if you could style a polymer custom element with CSS.  

Things have obviously changed, but the code for the attributes has not been kept up to date.  I find it makes for a really complicated implementation when you have two or more sources of variables that you have to prioritize, especially having two dimensions.  What if width attribute is provided but height is not? etc.  Not an excuse, but we could discuss how to resolve.

**Comment by Malvoz** [comment]
> I find it makes for a really complicated implementation when you have two or more sources of variables that you have to prioritize

By ensuring that the CSS that is generated from the provided `width` and `height` attribute values have low specificity the CSS Cascade would do that work for us.

> especially having two dimensions. What if width attribute is provided but height is not?

Similar to e.g. `<iframe>`, our maps have a default size of 300x150px, if the author provides only 1 of `width` or `height` then only that default dimension should be overridden.

In https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/167 I relied upon the low specificity we're achieving through `:host` for `<mapml-viewer>` or by appending styles as the [first element in the `<head>` for `<map>`](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/f3e4390f513fc7b5e79fec4f098925ba1bd07953/src/web-map.js#L164) (since `:host` is not applicable to `<map>` because it can't be a shadowroot host). The `width` and `height` attributes in that PR worked. Although that code was terrible, to my defense I don't know JS well and I did name the PR <q>provisional support</q>.

**Comment by erictheise** [comment]
Apologies if yesterday's question/comment was terse; it was more about surprise than criticism.

When I first shoehorned the element into our app I was puzzled that the map was so small but chalked it up to something our css or stack was doing. I returned to the issue after a day of different deadends and finally ended up here after inspecting a bunch of local css.

The `width` and `height` attributes feel familiar to an oldtimer like me and it would have been satisfying to see a 1200 x 800 map pop into view on that first page refresh. I'd favor provisional support over no support even if the vast majority of site builders will override their values.

**Comment by prushforth** [comment]
The code for width and height wasn't completely removed, when moving from polymer to Custom Elements 1.0. I'm not sure if that's a help or a hindrance, but we'll have to look more closely in order to prioritize this feature this fall.  It sounds like HTML 101, so should work for users like Eric.

Should the .width and height CSS properties be reflected to the attribute, or should the attribute be kind of write-only?  If we could discuss here, then reflect our discussion in the spec, then it would be easier to get the students to work on it with a clear spec.

**Comment by Malvoz** [comment]
> Should the .width and height CSS properties be reflected to the attribute

The other way around: the `width` and `height` attributes should be reflected in a `:host` declaration because it has lower specificity than that of CSS `width` and `height`, which means authors can override the HTML attributes using CSS (same as for iframe etc.).

W3C's [`<i-slide>`](https://github.com/w3c/i-slide) ([demo](https://w3c.github.io/i-slide/demo.html)) supports these attributes in that way:
https://github.com/w3c/i-slide/blob/f6747ab6e15e8de5347ba20ab0a8757e3a29bfdd/ISlide.js#L704-L724

> reflect our discussion in the spec

I don't think there's anything to change, we already state that the map element supports the HTML dimension attributes: https://maps4html.org/MapML/spec/#attr-map-width
