### ISSUE TITLE
Text instructions for keyboard shortcuts and the query reticule

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#267]

**Comment by Malvoz** [comment]
By "text instructions" do you mean instructions for how to operate it (keyboard shortcuts)?

**Comment by prushforth** [comment]
Yes, maybe it needs them just as the a11y map and Google Maps do when the focus area is visible?

**Comment by Malvoz** [comment]
I've renamed this issue to include text instructions for keyboard shortcuts in general as well.

Since last year when we reported accessibility issues in Google Maps at the time of the W3C/OGC Maps for the Web workshop they've made a ton of improvements (related [blog post](https://cloud.google.com/blog/products/maps-platform/improved-accessibility-maps-javascript-api)), including a new "keyboard shortcuts" button placed next to the attribution links:

<img width="350" src="https://user-images.githubusercontent.com/26493779/143273122-20243cc9-5304-4103-8c02-3fb8150d8bac.png">

which opens up a dialog with text instructions:

<img width="500" src="https://user-images.githubusercontent.com/26493779/143273164-8f73c200-f412-4425-a471-c5537b434b9d.png">

A dialog like this could hold instructions for keyboard shortcuts such as pan, zoom, context menu, and the query reticule.

**Comment by prushforth** [comment]
It's great, your advocacy has had an impact on Google Maps too, by the looks of it.  It would be **greater** if they all came over here and helped us improve our proposal.  Not that you can do anything about that, mind you. I guess I'm happy to try to implement accessibility improvements to the polyfill as we can, including this one.
