### ISSUE TITLE
<g> element <path> children's <title> values are not read

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#332]
Leaflet renders vector info [as SVG `<path>`s](https://maps4html.org/experiments/index.html), which it groups into a single `<g>` element.  Each feature you create is rendered as a path inside that `<g>`, and we have successfully added a `<title>` to each one, anticipating that it might be read by screen readers.

While the "g" is announced (on chrome, "blank" on FireFox) for each `<path>` inside the `<g>`, the path's `<title>` value doesn't get read.  If I remove the `<g>`  in devtools (re-parenting the `<path>`s to be children of `<svg>`) , both "g" and the `<title>` value are announced (using NVDA in Chrome. I tried that trick with FireFox but the tab crashed).  Is there some way to convince screen readers to look inside a group for path titles ?

I think @shepazu may have already written the answer to this in [blog post](https://fizz.studio/blog/reliable-valid-svg-accessibility/#best-practice-2-aria-label-not-title) form: `<path aria-label="accessible name"...>` attribute instead of (as well as??) `<path><title>`

cc @Malvoz

**Comment by prushforth** [comment]
I think the reason that there were issues with the <title> element was because it was being created with document.createElement. So I believe [this PR](https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/333) fixes the screen reader issue.

**Comment by prushforth** [comment]
While the PR did fix the screen reader issue, mostly, it didn't fix it for the first path in the group; at least, you have to tab past the first path and then shift-tab to it, and then it is read.  But it's better than it was.  If you have an idea about how to solve this latter problem, please comment.  I'll close this issue for the time being.

Of note is that this latter problem exists in both Chrome and Firefox.

**Comment by Malvoz** [comment]
> for [the first path in the group](https://maps4html.org/experiments/index.html); at least, you have to tab past the first path and then shift-tab to it, and then it is read.

Screen readers seem to have problems with nested interactive elements (map features are nested interactive elements inside `leaflet-container` which has `tabindex="0"`). I don't think there are many (if any) interactive elements except for `<summary>` that allow interactive content as descendants per the HTML spec so that's probably why screen readers don't handle it well. If `tabindex="0"` is removed from `leaflet-container` the first path in the group is announced correctly.

If `role="application"` (https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/274) is applied to `leaflet-container` the first path in the group is announced correctly.

Setting [`aria-live="polite"`](https://www.w3.org/TR/wai-aria-1.1/#aria-live) on the tooltip can be used to "force" screen readers to announce that content, but I think that'll ultimately end up with screen readers announcing both `<svg><title>` _and_ the tooltip. And because they're identical that could be pretty annoying.
