### ISSUE TITLE
How can we get rid of the scrollbars on the map

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#350]
For some reason, scrollbars show up on some maps, but not others, and I'm wondering if we can banish them, since the primary means of navigating the map is pan/zoom provide by other  means.

**Comment by Malvoz** [comment]
I believe the only cases where scrollbars would show up is when the map is covering the entire document, such as in the [Ottawa Restaurants experiment](https://maps4html.org/experiments/index.html). This is expected, because the size of the map element (`width: 100%; height: 100%;` relative to the body) + the [default `border-width` of 2px](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/f00dfeed36fb7e6db03ae1c05d9536c6c8fb9729/src/mapml-viewer.js#L117) is larger than the document so it's overflowing the document itself. The same would happen if you set width/height to 100% for an iframe as well.

There are different ways to go about ensuring scrollbars don't show up (together with `max-width: 100%` for responsiveness):
- Set [`box-sizing: border-box;`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing) on the map element. In fact this is useful as a global rule, and is used in many "CSS resets", for example in [CSS Remedy](https://github.com/jensimmons/cssremedy/blob/b8b3ce7204901d2dfd5941f4f777b1af3879ed54/css/remedy.css#L21).
- Remove the border from the map element using either CSS `border: none` (or HTML `framborder="0"`, this is generally not recommended because it is deprecated, but I thought we could [support it](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/f00dfeed36fb7e6db03ae1c05d9536c6c8fb9729/src/mapml-viewer.js#L120-L122) just as it is supported in most/all browsers for iframes)
- Set `html { overflow: hidden; }`. This solution is very situational, it would work well in cases where the map element is the only element on a web page.

**Comment by Malvoz** [comment]
I can add the `*, ::before, ::after { box-sizing: border-box; }` global rule to our inline styles of all HTML documents for demo/test pages in this repo. I don't think I have write access to https://github.com/Maps4HTML/experiments/ though.

**Comment by prushforth** [comment]
Thanks for these suggestions, I'll play around with them and see if I can get a better feel for it.

**Comment by Malvoz** [comment]
While we _could_ make the map viewers `box-sizing: border-box` by default, this is unlikely to be the case in a standardized map viewer, so if we did that authors would not set `box-sizing: border-box` when using the polyfill because they don't get these awkward borders, but once there's a native implementation and the polyfill does not apply then everyone would all of a sudden have these borders on their maps (under the conditions that they create an overflow on the document).

Also, I see that there are still borders happening in the experiments repo, I'll fix those.

**Comment by Malvoz** [comment]
OTOH, because we set `all: initial` (https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/141/), applying the `*, ::before, ::after { box-sizing: border-box; }` reset does not always work (if set from an external style sheet as opposed to inline `<style>`).

Perhaps a compromise is to add `box-sizing: inherit;` in:

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/ae0364098a43ccaa34b9ab4a42b82b5f34df52dd/src/mapml-viewer.js#L115

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/ae0364098a43ccaa34b9ab4a42b82b5f34df52dd/src/web-map.js#L122

I'll give this more thought & testing later.

**Comment by Malvoz** [comment]
To remove the scrollbars in Firefox, `vertical-align: middle` is also required...

**Comment by Malvoz** [comment]
The following styles should ensure a map that isn't larger or wider than 100% should never cause scrollbars:

```css
*, :: before, ::after {
  box-sizing: border-box;
}

body {
  margin: 0;
}

mapml-viewer {
  border: 0;
  max-width: 100%;
  vertical-align: middle;
}
```

**Comment by Malvoz** [comment]
The following styles should ensure a map that isn't larger or wider than 100% should never cause scrollbars:

```css
*, ::before, ::after {
  box-sizing: border-box;
}

body {
  margin: 0;
}

mapml-viewer {
  max-width: 100%;
  vertical-align: middle;
}
```

**Comment by Malvoz** [comment]
Closing per https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/350#issuecomment-870967364. To be documented (https://github.com/Maps4HTML/web-map-doc/issues/26).

**Comment by Malvoz** [comment]
One difference between `<map is="web-map">` and `<mapml-viewer>` is that a declaration such as:

```css
*, ::before, ::after {
  box-sizing: border-box;
}
```

does not seems to entail the `map` element. Despite using the [`*` universal selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Universal_selectors). This is why e.g. the [progressive enhancement demo](https://maps4html.org/experiments/progressive-enhancement/) has scrollbars. This is true both in Chrome and Firefox. I think, historically, `<map>` hasn't been considered subject of styling, I would say customized built-in elements changes this notion. Perhaps I should file browser bugs.

For this reason we should set `box-sizing: inherit` for `<map is="web-map">`, such that both elements behave the same when the (very common) global box-sizing declaration is used.
