### ISSUE TITLE
Temporarily suspend interactivity if layer is not "on top"

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#391]
When adding templated layer of whatever type, layers with vector data lower in the z-order currently retain their interactivity, such as links and popups.  

This issue is to discuss how to handle interactivity in lower (non-top) layers.  

I think it would add coherence to the product if we applied the "only the top layer can be queryable OR interactive" rule, so that only the top most layer can be interactive, regardless of whether it's feature data or queryable imagery.

In a native code implementation, we'll hopefully see, perhaps interactivity could be determined at the graphics level: whatever layer rendered the final topmost value of a pixel could get to make that pixel interactive.

**Comment by Malvoz** [comment]
> I think it would add coherence to the product if we applied the "only the top layer can be queryable OR interactive" rule, so that only the top most layer can be interactive, regardless of whether it's feature data or queryable imagery.

I think this would be a bit unfortunate though as it'd be quite limiting on both authors and users. e.g. if the author wants to display 2 sets of layers with markers I assume only 1 set of markers would be interactive even if both sets are visible. Users would have to toggle layers to be able to interact with the otherwise non-interactive markers. And maybe that's fine in a polyfill, or it's  expected of us to solve things like this...

With the risk of complicating things - my specialty - I wonder if we can hack this using `mix-blend-mode` (https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/305):

```css
.mapml-layer {
  mix-blend-mode: multiply;
}
```
### No `mix-blend-mode` (current)
<img width="350" src="https://user-images.githubusercontent.com/26493779/114697502-478dff00-9d1e-11eb-9bd8-d97663301946.png">

### With  `mix-blend-mode: multiply`
<img width="350" src="https://user-images.githubusercontent.com/26493779/114697522-4d83e000-9d1e-11eb-824e-f15ce48b5bd4.png">

(some features have transparency, which doesn't seem ideal for e.g. markers)

### With  `mix-blend-mode: darken`
<img width="350" src="https://user-images.githubusercontent.com/26493779/114705495-17e3f480-9d28-11eb-8ff5-2b0acdd89231.png">

(some features are seemingly not transparent, e.g. markers)

This blend hack may be using `mix-blend-mode` naively, even if improved it may still not be perfect, but it allows preserving interactivity of all features since they're now visible to the user.

But, we'd still have the issue of having 2 or more interactive features stacked on top each other (whether belonging to same or different layer), touch- and mouse pointer users would still have to re-order layers to interact with the initially underlying one. A [Feature Index](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/397) could allow these users to interact with stacked features.

**Comment by ahmadayubi** [comment]
In the PR instead of only making the top layer interactive, it just checks for a queryable layer on top, if it has one then the layer losses intractability, if not then it remains interactive even if there are other layers on top, as long as the feature is visible and clicked it'll follow the feature link rules.
