### ISSUE TITLE
Panning via touch fails after following a link

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#411]
On Firefox and Chrome on Android, you lose the ability to pan immediately after following a link. You get it back after a single zoom.
Test it [here](http://maps4html.org/experiments/custom-projections/Arctic-SDI/)

**Comment by Malvoz** [comment]
I think this is true for all browsers. This is because after you've followed a link it is the `<body>` element that receives focus and not the map viewer.

**Comment by prushforth** [comment]
Thanks for that knowledge, Robert! Seems like something we should control in th   is case, since they're in-map links.

**Comment by Malvoz** [comment]
Unless I'm missing something, map links currently work differently from regular `<a>` links ("local" links in this case) since there is no focus sent to the target destination. For example if I visit that URL and click Greenland then `<g tabindex="0" aria-label="Greenland" ...>` should ideally recieve focus.

And if that feature for some reason is missing then at the very least `<div class="leaflet-container">` should recieve focus, not `<body>`.
