### ISSUE TITLE
Refactor MapML elements as custom elements

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#511]
Per https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/174, it seems like a best practice of Web platform speculative polyfills is to generate proposed new APIs in a separate namespace, so that the name of the polyfills doesn't collide with the eventual standard name. 

For elements, that implies today that we should use custom elements, and if I understand correctly, probably also data- prefixed attributes. Customised built-in elements would be ideal for implementing proposed extensions of existing elements, while autonomous custom elements would better serve the use case of new elements.  There is apparently a viable polyfill for customized built-in (is=), but unsure how it works. It may not be worth the trouble of using the polyfill, opting instead for a apec explanation of the intended name of the eventual element.

This issue is for discussion of how to approach this refactoring.

We'll also need to decide how to do this in the draft spec, so that it's clear whether a proposed.element is 'new', or an extension of an existing element.

Also see https://github.com/Maps4HTML/MapML/issues/215#issuecomment-917656635

**Comment by Malvoz** [comment]
> probably also data- prefixed attributes

Just noting that IMO the situation regarding "custom" attributes vs `data-` prefixed attributes (related: https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/191) is much less important than converting the MapML elements to custom elements containing a hyphen. Especially so if the attributes are used only on custom elements, since that wont "pollute" standard HTML elements. So perhaps this issue can focus solely on the elements aspect?

**Comment by prushforth** [comment]
Yes, for now we'll focus on elements.  What's your opinion on the `<mapml>` element?

**Comment by Malvoz** [comment]
All MapML elements must contain a hyphen, so it'd be `<mapml->`. In the spec and the explainer the elements should be referred to without hyphens.

**Comment by prushforth** [comment]
Ok, I went with `<mapml->`, but everything else (except `mapml-viewer` and `layer-`) I put into the `map-` "namespace".  ok?

We'll need to explain this somehow, perhaps in the MapML spec?

**Comment by Malvoz** [comment]
I don't think there's a need to use a `map-` prefix. The MapML spec should name elements as they're intended to be standardized. But the polyfill must follow the HTML custom components rules, so they're required to include a hyphen.

The intention is then that when the spec is mature and browsers are ready to implement it _and_ the polyfill follows the spec exactly (the [tipping point](https://www.w3.org/2001/tag/doc/polyfills/#tipping-point)) we're safe to remove the hyphens because now the polyfill is guaranteed to match the behaviors of the standard.

**Comment by Malvoz** [comment]
Fixed in https://github.com/Maps4HTML/Web-Map-Custom-Element/commit/c67198ba4c72b0199a2428a1918a778686088b0c. 

Thanks to everyone involved!

**Comment by prushforth** [comment]
> Thanks to everyone involved!

Thanks to you, too, for motivating some change for the better.  Hopefully any bugs are minor.
