### ISSUE TITLE
Rename 'master' to 'main'

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#512]
I'll wait to do this until a day that @ahmadayubi is available to help verify the github actions won't be broken long term

**Comment by ahmadayubi** [comment]
I believe the line below is the only line that needs to be updated for this change: 

 - https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/f3e4390f513fc7b5e79fec4f098925ba1bd07953/.github/workflows/sync.yml#L6

I also believe the repository secrets and everything else related to actions should work fine after the change, most actions just rely on the default branch regardless of the naming.

If this is a change you feel is useful it may be good to update other repositories Maps4HTML controls too, simply for the sake of consistency. When checking out of branches you'd know everything MapML related is going to be main rather than having to guess if it's main or master.

**Comment by Malvoz** [comment]
Probably useful: https://github.com/github/renaming#renaming-existing-branches

**Comment by prushforth** [comment]
This is now done. To update your local clone:

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
