### ISSUE TITLE
M.extractInputBounds fallback bounds

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#576]
@ahmadayubi  this test [Template with missing easting and northing input](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/31ad0bd0b392bd10f40527efd0185af70bd54562/test/utils/boundsUtils.spec.js#L247) seems to [expect a bounds](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/31ad0bd0b392bd10f40527efd0185af70bd54562/test/utils/boundsUtils.spec.js#L257) that is not as far as I can tell, the appropriate fallback bounds for the WGS84 "pcrs",  which [should be](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/31ad0bd0b392bd10f40527efd0185af70bd54562/src/mapml/index.js#L103): `{ bounds: { max: { x: 180, y: 90 }, min: { x: -180, y: -90 } }`  What am I missing?  Thanks

EDIT: I **think** the function `M.boundsToPCRSBounds` is wrapping the x axis at pcrs.x = 180, so maybe that's the reason (??)

**Comment by ahmadayubi** [comment]
It's an error in the function _I think_. It take into account `<map-input name="zoomLevel" type="zoom" value="2" min="1" max="5"></map-input>`'s value attribute provided. So in this case the value = 2, internally it takes the tilematrix bounds at zoom level 0 (as the fallback), but it's treating them as if they were the bounds at zoom level 2 (rather than 0). 

So for the test it seemed like the right value because when converting the tilematrix bounds `{ min: { x: 0, y: 0 }, max: { x: 2, y: 1 } }` with zoom = 2, it generated the expected values. 

Error being it should consider value as 0 when easting and northing are missing. But I guess not in the case where only a single one is missing. i.e. when easting is provided but northing isnt. It's a complex interaction but definitely a bug.

**Comment by prushforth** [comment]
Yes, it's not so much a bug in the code as it seems to be a problem of underspecification, which falls to me.  I will fix it, I am working on it now.

**Comment by ahmadayubi** [comment]
> Yes, it's not so much a bug in the code as it seems to be a problem of underspecification, which falls to me. I will fix it, I am working on it now.

It falls on the code too, it's definitely a bug/oversight on my part (this was early on). I actually have a PR I'm about to submit to fix this.

**Comment by prushforth** [comment]
OK it's a bit ugly, but I was wondering what you think about the logic [here](https://github.com/prushforth/Web-Map-Custom-Element/blob/5d0e7414167bf1f401608cddf92fdb7a59bd918f/src/mapml/utils/Util.js#L133).  I added the template.extentFallback.bounds over [here](https://github.com/prushforth/Web-Map-Custom-Element/blob/5d0e7414167bf1f401608cddf92fdb7a59bd918f/src/mapml/layers/MapLayer.js#L682).  I updated the [TemplatedFeaturesLayer.js](https://github.com/prushforth/Web-Map-Custom-Element/blob/5d0e7414167bf1f401608cddf92fdb7a59bd918f/src/mapml/layers/TemplatedFeaturesLayer.js#L192) to make it match the logic of the TemplatedImageLayer, more or less.

**Comment by ahmadayubi** [comment]
LGTM, the one case that _may_ cause issues is where a `type=location` is provided but only for 1 of the axes and a zoom value is provided.

I think it needs to make sure a `type=location` is provided for both axes for it to work as expected.
