### ISSUE TITLE
type extension elements discouraged

### ISSUE THREAD

**Issue by elf-pavlik** [Maps4HTML/Web-Map-Custom-Element#65]
https://www.polymer-project.org/2.0/docs/about_20#type-extension

> Polymer 2.0 doesn't support type-extension elements (for example, <input is="iron-input">). Type-extension support is still included in the custom elements v1 spec (as "customized build-in elements"), and scheduled for implementation in Chrome. However, since Apple has said it will not implement is, we will not be encouraging its use to avoid indefinite reliance on the custom elements polyfill. Instead, a wrapper custom element can surround a native element.

Maybe README and demo should simply use

```html
<web-map ...>
```
instead of
```html
<map is="web-map" ...>
```

**Comment by prushforth** [comment]
I'm still holding out hope that Polymer 2.x will support type extensions.  I wrote a [blog post](http://maps4html.github.io/Web-Map-Custom-Element/blog/progressive-web-maps.html) about why I think its important to go with &lt;map is="web-map"&gt; All that said I understand that Safari is unlikely to come around.  I put an issue in with the Polymer project to support the is attribute in v 2.x, and although I can't find the link right now, I'm hoping they will add support 'soon' after release of 2.0.  I know Chromium is working on support for is, so its not quite dead yet.   When/if it does become evident that is is dead, I will re-write the element as web-map.  Thanks for your input.  Will leave this open until a decision can be reached.

**Comment by prushforth** [comment]
After much anxiety over this, I've decided to re-write the web-map custom element as an autonomous element.  I believe there are good reasons for wanting to extend the &lt;map&gt; element, but custom built-in elements which allow `attachShadow()` would seem to [compromise the future of the native elements](https://github.com/w3c/webcomponents/issues/734#issuecomment-366724291) that should / could be enhanced in the future Web platform. 

In the interest of enhancing the functionality of the web-map custom element as a "proxy" for a polyfill, or a "proxyfill", I accept the premise of this issue and will re-write the element as autonomous.  The element needs a lot of new features to better support MapML and it has been kind of stuck on Polymer 1.0 for > 1 year because of the dropped support for custom built-ins in that library.  Even with the pending support for custom built-ins in Firefox and presumably Chrome, the fact that the (map) element definitely needs a shadow root to protect styles but that adding a shadow root to &lt;map&gt; would compromise any future ability of the platform to use that shadow root for anything is the reason we should avoid tampering with the &lt;map&gt; element **at this stage**.

Instead of trying to convince by providing [working examples](http://maps4html.github.io/Web-Map-Custom-Element/blog/progressive-web-maps.html), I will opt to ask the reader to discuss the practicalities of introducing a new element into the platform, given that new elements typically take years to be supported across all browsers.  The discussion should centre on how HTML authors will provide fallback behaviour for the new mapping element(s).

In the mean time, I will leave this open, and will close it when the new autonomous implementation of the web-map element is ready.  I think I'll leave the proposed spec for the [&lt;map&gt;](https://maps4html.github.io/HTML-Map-Element/spec/) element as it stands since nothing in the custom element's design so far compromises that proposal.

**Comment by prushforth** [comment]
Although we still maintain the web-map.js custom built in as a way of demonstrating progressive enhancement of existing HTML elements, since Safari has no plans to support custom built in elements, we are currently relying on the autonomous mapml-viewer map element as a way to provide the functionality of a standard web map across the custom-elements-supporting platform.  So closing this; if there's more to say, feel free to add to the conversation anyway.
