### ISSUE TITLE
Page jumps when keyboard query activated

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#694]
https://geogratis.gc.ca/mapml/en/cbmtile/fdi/

When the \<mapml-viewer> is a block element in a scrollable page, and the query reticle is displayed (because the map has focus), hitting spacebar (activating the query) causes the page to quickly and annoyingly scroll down then up.  Hitting Enter also activates the query, but not the annoying scroll jump.

This doesn't happen when the map is the whole page, for example when fullscreen is active.

**Comment by Malvoz** [comment]
<kbd>Space</kbd> to scroll down is generally expected in normal documents, the scroll up happens because the popup receives focus.

It does make sense to prevent scroll down if the map element is focused. Such behavior can be seen in the `<select>` element (at least in Chrome), where <kbd>Enter</kbd> selects the focused option, and while <kbd>Space</kbd> does nothing, it also does not scroll the document.
