### ISSUE TITLE
Create a `map-extent` checked attribute

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#786]
Currently, there is no checked attribute for a `<map-extent>`, yet the extent is checkable in the layer control if it has a `label` attribute. Even though there is currently no custom element for `<map-extent>` we should enable such a boolean attribute in preparation for creating a custom element version.  The `checked` attribute would in this case control the initial state of the extent when loaded and first displayed.

Some issues that we may encounter:

- basically no single-extent layers that we've created so far have a `checked` attribute, so we would have to go back and add a checked attribute for them to be on by default. In other words, a backwards-incompatibilty with existing content

- only `<map-extent>` elements that have a `label` attribute are exposed in the layer control, so if an unlabeled extent has its `opacity="0"` then checking / unchecking the layer will have no visual effect on the map, which could be hella confusing.

- for the latter issue, we could either change the behavior of the layer control to show those unlabeled extents anyway OR we could devise a rule whereby unlabeled extents with an opacity attribute are shown / have a label generated so that they're shown.

**Comment by prushforth** [comment]
As far as a `checked` attribute goes, I think we should define that an _unlabeled_ extent is `checked` at page load (**generate the attribute**).  I note that actual `<input type=checkbox ... checked>` inputs don't actually change the value of the`checked` attribute as the user updates them; [only the `.checked` property changes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#checked).   An extent with a `label` attribute is exposed in the layer control and should thus be under the explicit control of the author, who wishes it to be exposed, so no checked attribute should be generated for labeled extents.  We will have to go back and change all examples with labeled extents to include the `checked` attribute.  We should make an example of a labeled extent with no `checked` attribute to explicitly demonstrate the rule.  This behaviour should be [specified](https://maps4html.org/MapML/spec/#the-extent-element-0), and described in the spec.

**Comment by prushforth** [comment]
We have been [working on](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/886) the \<[map-extent](https://maps4html.org/MapML/spec/#the-extent-element-0)> custom element implementation.  ([experiment](https://maps4html.org/experiments/multiple-extents/)).  The `checked` attribute is a thorny issue: are we violating [this a11y principle](https://accessibilityinsights.io/info-examples/web/nested-interactive/) by designing nested interactive elements into MapML?  How can we avoid / mitigate this? (The \<map-extent> element is a nested child or shadow DOM descendant of \<layer->, which also has a `checked` attribute, so they're both interactive, and nested).  

The intent here is not to nest a button inside a button, or similar accessibility trap, but to represent interactive controls for map content in a form-like manner using their declared structure (nesting and attributes).

Currently, [we have not documented](https://maps4html.org/web-map-doc/docs/elements/extent/) the `checked` attribute of the \<map-extent> element, but if it's to be checkable (as [it currently is in the layer control layer settings](https://maps4html.org/experiments/multiple-extents/)), I believe it should have the possibility of a `checked` attribute, [per spec](https://maps4html.org/web-map-doc/docs/elements/extent/) (maybe/probably the spec needs change too).

Thanks for any thoughts you may have on this.

cc @Malvoz @AmeliaBR @shepazu @nchan0154

**Comment by nchan0154** [comment]
@prushforth
This is definitely very tricky! I feel like it's one of those things where the implementation really determines whether or not you've violated the 'no nested interactive controls' rule. In the working example, care has been taken to make sure none of the controls are actually nested and that it does work with the keyboard, but I wonder if the component is 'doing too much'. The control is complex enough that it simultaneously resembles a [tree view](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/) as well as a <details> + <summary> element but there are additional form inputs nested within the view, and because of that it doesn't map neatly to either set of semantics.  There is also mouse drag and drop that doesn't appear to be implemented for the keyboard, but adding it would muddy the waters further. The map-extent element itself being the one to have all these attributes may be confusing, especially for screen reader users.  I'm not too familiar with the spec aspect (ie. if any other controls have this level of functionality in a single control, or if it's common for 'subcontrols' to determine a parents state), but I think now would be a good time to do some testing with/solicit feedback from a wider population.  

Some questions/other thoughts I had when looking at the experiment that are worth considering from an accessibility perspective:
- The use of hover to open the layers control makes the drag and drop very particular, it's easy for the action to get interrupted by the mouse leaving the bounds of the window
- There are currently 3 controls that have slightly different, but similar functions of 'hiding a layer' (ie. toggling visibility, complete removal, opacity). Do we need all 3? My gut feeling is that removing a layer is the least useful here and getting rid of that control could simplify the UI, but perhaps there are use cases I haven't considered?
- Does each layer control need to be it's own disclosure widget? In the example, it feels like there is enough room to have both input and label be shown without the need for a disclosure widget.
- [This blog post is food for thought](https://ericwbailey.design/published/equivalent-experience-can-cut-both-ways/)

**Comment by yhy0217** [comment]
Resolved to #887, horizontal review from W3C accessibility community is required.
