### ISSUE TITLE
Demo has issues

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#79]
In the demo at https://maps4html.github.io/Web-Map-Custom-Element/ alot of resources from https://geoappext.nrcan.gc.ca returns 404. It seems [Cross-Origin Resource Blocking](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md) (CORB) is in effect.

**Comment by prushforth** [comment]
Yes, I noticed that.  There are a couple of issues.  First the client currently doesn't well respect the bounds that are set up by the `<input type=location min=... max=...>` elements in the `<extent>`.  That will help alleviate some 404s when I'm able to fix that.   Next, the service for the CBMT has recently (I think) started returning text/html instead of a blank image/*.  That is why the CORB message is happening, I believe.    I did report this to the service owner and asked to get a blank image returned instead of the text/html.  But vacations being the thing right now I'm not sure when it will get addressed.

The demo is also on a very old version of the client.  Hopefully will get some time in the fall to bring everything up to date. 

I will close this issue when I get the CORB problem addressed.  Thanks for commenting.

**Comment by Malvoz** [comment]
Thanks @prushforth, my intention of using the demo today was to inspect image requests when navigating the map. There's alot happening in the world of images (and embeds) on the web concerning performance and user bandwidth, e.g: image [`decoding`](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-decode), [`lazyload`](https://github.com/whatwg/html/pull/3752), [priority hints](https://www.chromestatus.com/feature/5273474901737472) and also [CSS containment](https://www.w3.org/TR/css-contain-1/).

Is this something you'd care to look at? Obviously this too applies to Leaflet, I may instead open an issue over there. However if (when?) Maps4HTML stop relying on leaflet these are still things to consider.

**Comment by prushforth** [comment]
Leaflet is great, and its code has been how I learned what is good quality code, not that I reproduce that quality usually. As time goes by, I hope to move to first no dependencies and then to native code.

But if such considerations apply to the `<img>` element, then they probably will apply to the MapML `<tile>` and `<image>` elements as well, so bring it on as necessary; please post a link back here from your Leaflet issues, and I will follow those individually.

**Comment by Malvoz** [comment]
There you go!  :) [Leaflet/issues/6283](https://github.com/Leaflet/Leaflet/issues/6283)

**Comment by Malvoz** [comment]
No CORB issues anymore AFAICT, closing.
