### ISSUE TITLE
Handle fullscreen declaration(s)?

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#83]
<s>Add [`allow="fullscreen"`](https://w3c.github.io/webappsec-feature-policy/#iframe-allow-attribute) and/or deprecated [`allowfullscreen`](https://w3c.github.io/webappsec-feature-policy/#iframe-allowfullscreen-attribute) attributes to `<map>`, if either declaration is present</s> invoke [fullscreen control for Leaflet](http://leaflet.github.io/Leaflet.fullscreen/) if `controls` is present, unless `controlslist="nofullscreen"` is specified.

Use case: https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#use-case-fullscreen

**Comment by Malvoz** [comment]
Might be worth checking out @runette's [fork](https://github.com/runette/Leaflet.fullscreen).

**Comment by prushforth** [comment]
Thanks for the updated allow="fullscreen" vs allowFullScreen.    Do you think we should go with allow=, since allowFullScreen is deprecated?  The prose around allowFullScreen leads into deep browsing context waters, but I think there's a big discussion to be had about the map element's layers potentially each being a browsing context.   But that should probably be a separate issue.

> Might be worth checking out @runette's [fork](https://github.com/runette/Leaflet.fullscreen).

Yes that would likely be pretty easy to add into the project.  I was surprised that (Chrome) did actually allow it to go fullscreen even using http (I thought fullscreen was only allowed in https).

**Comment by Malvoz** [comment]
My intention with this was to have the `<map>` function similar to `<video>` but what I suggested is not how that works. `<video controls>` means fullscreen button is visible, and adding [`controlslist="nofullscreen"`](https://wicg.github.io/controls-list/html-output/multipage/embedded-content.html#attr-media-controlslist) disables it.

**Comment by prushforth** [comment]
I have been playing around with this, and I can get it to work, but because the map container is in a shadow root, when the fullscreen event is generated, I believe it [retargets ](https://fullscreen.spec.whatwg.org/#dom-document-fullscreenelement)the fullscreen element from the map container div to the ancestor div that contains the shadow root. So it doesn't correctly set the classes associated to the fullscreen-on state.  All this to say if I include this library I will have to change the code a bit, so we'll own it.  I don't think that's too big an issue, because the code isn't too big or complicated.  What do you think? @Malvoz

**Comment by prushforth** [comment]
Actually I find I can make the modifications with the build process, so as long as the text of the code stays stable, it should work.  I'll commit and send a pull request you can check it out.

**Comment by Malvoz** [comment]
My intention with this suggestion was for `<map>` to work similarly to `<video>`, but I got it wrong, for video, the fullscreen button is always available, but removed when `controlslist="nofullscreen"` is present.

**Comment by prushforth** [comment]
@Malvoz So I won't make a pull request, maybe you can just fork my [repo](https://github.com/prushforth/Web-Map-Custom-Element) and see what you think. There's more stuff to do but maybe you'll have an opinion at this point.

**Comment by prushforth** [comment]
> or video in a top level browsing context, the fullscreen button is always available, unless controlslist="nofullscreen" is present.

I thought you had mentioned that somewhere but I couldn't find where!  That's the stuff I still have to do.  Anyway it works temporarily with allow="anything".

**Comment by Malvoz** [comment]
> I thought you had mentioned that somewhere

https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/16

**Comment by Malvoz** [comment]
> fork my repo and see what you think

Looking good!

I could see how a native map viewer would have to require `allow="fullscreen"`, but for this custom element which isn't a nested browsing context it seems strange to use `allow`. What's your opinion on displaying the fullscreen button by default, and only removing it if the `controlslist` attribute contains the `nofullscreen` directive, instead? While I'd like to remind you that the [Controls List API](https://wicg.github.io/controls-list) is [not yet](https://github.com/whatwg/html/pull/2426) in the HTML standard, [Chrome reports](https://www.chromestatus.com/metrics/feature/timeline/popularity/1853) it is used on almost 4% of all page loads.

It's hard to say which type of controls would be good as defaults for web maps. But I think especially for mobile devices a fullscreen button would be appreciated by users.

**Comment by prushforth** [comment]
Ok I pushed some updates to my [repo copy](https://github.com/prushforth/Web-Map-Custom-Element/commit/167e30c02e665e9d0a737a178edbad2d327d4e01): replaced `allow="fullscreen"` with `controlslist="nofullscreen"`, since that seems to be what will [happen](https://wicg.github.io/controls-list/#solution-outline). I personally like this, because it allows you to individually remove controls and replace them, instead of having to replace all controls when you don't like one of them.  We will have to think up how to [add a custom control](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/79), per the requirements, but that is a bit ahead of us now.

To do before making a pull request:

- [ ] think up and add support for "noxxx" for zoom, layer controls - maybe after PR(?)
- [ ] design and implement a test for this feature
- [ ] add controlslist to the [spec](https://github.com/Maps4HTML/HTML-Map-Element)
