### ISSUE TITLE
`.mapml-control-layers` invalid HTML

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#88]
<details><summary>HTML</summary>

``` html
<form class="leaflet-control-layers-list style-scope web-map">
    <label class="style-scope web-map">
        <details class="mapml-control-layers style-scope web-map">
            <summary class="style-scope web-map">
                <input type="checkbox" class="leaflet-control-layers-selector style-scope web-map">
                  <span draggable="true" class="style-scope web-map" style="font-style: italic;">
                    Canada Base Map - Transportation (CBMT)
                 </span>
            </summary>
            <details class="mapml-control-layers style-scope web-map">
                <summary class="style-scope web-map">opacity</summary>
                <input type="range" min="0" max="1.0" value="1.0" step="0.1" class="style-scope web-map">
            </details>
        </details>
    </label>
</form>
```

</details>

nuvalidator output:

> Error: Element `details` not allowed as child of element `label` in this context. (Suppressing further errors from this subtree.)
>
> Error: The `label` element may contain at most one `button`, `input`, `meter`, `output`, `progress`, `select`, or `textarea` descendant.
>
> Warning: `label` element with multiple labelable descendants.

The real world issue here is that none of the input elements have an accessible name and as such inaccessible to screen readers.

**Comment by prushforth** [comment]
Is is as simple as giving them a name attribute? Seems there's a validation error to be concerned about as well (perhaps).

**Comment by Malvoz** [comment]
You can nest `<input>` in a `<label>` element to provide the input an accessible name like so:

``` HTML
<label>
  <span>the accessible name</span>
  <input type="range">
</label>
```

Or if nesting isn't desirable you can assign the input and ID and reference it from the label using the `for` attribute:

``` HTML
<label for="a">
  <span>the accessible name</span>
</label>
<input id="a" type="range">

<!-- or -->

<input id="b" type="range">
<label for="b">
  <span>the accessible name</span>
</label>
```

Example using `<label>` within `<summary>` as the accessible name for the input:

```HTML
<details>
  <summary>
    <label for="c">the accessible name</label>
  </summary>

  <input id="c" type="range">

</details>
```

Most browser developer tools today have an accessibility tab where you can view the computed accessible name (amongst other things).

**Comment by prushforth** [comment]
OK I'll have a look. Thanks!

**Comment by Malvoz** [comment]
Does this achieve what you want? View it [here](https://maddening-experience-20mnirlhz7.glitch.me) ([source](https://glitch.com/edit/#!/maddening-experience-20mnirlhz7)):

```HTML
<style>
    fieldset {
        border: none;
    }
    
    [type="range"] {
        display: none;
    }
    
    [type="checkbox"]:checked ~ [type="range"] {
        display: block;
    }
</style>

<form>
    <fieldset>
        <input id="a" type="checkbox">
        <label for="a">
            <span>Canada Base Map - Transportation (CBMT)</span>
        </label>

        <input type="range">
    </fieldset>
</form>
```

**Comment by Malvoz** [comment]
I forgot to add a label to the second input in the latest example, updated.

**Comment by prushforth** [comment]
Can't see it on my phone - I'll check it out soon on my puter- in the middle of Sunday cooking spree ATM 😅. The markup is generated by my code. I never bothered to validate the result.

**Comment by prushforth** [comment]
It's close.  The reason I used details / summary was to allow hiding of layers' child inputs that are not currently of interest to the user.  I can't recall why I ended up with the label wrapping the whole thing, but I think it was to have the checkbox and label side-by-side as in your glitch, but also to enable hiding of sub-controls in the same way.  You can see that the nesting of the details elements is what gives that effect, and I can't recall why the label wraps them all.  Maybe I thought that the whole set of controls and associated text was a label for the layer.  I will tinker with it to see if I can modify the labeling to match the need.  tbh I am open to any sort of change that helps accessibility, but there are also some functional challenges and potentially some security concerns in this little space too!  For instance, the mapml <extent> element can contain some controls (input, select) that the user can manipulate to select a variable value, that then is used to control the map content queries.  Here's an [example](http://geogratis.gc.ca/api/beta/mapml/static/territorial_evolution.html) of that, in which a select is copied from the mapml document into the layer control.  I think this is an area that needs some more research, because it could be a powerful way to allow the user to control the query that generates the map, but at the same time it needs to be sandboxed (I think).

**Comment by Malvoz** [comment]
> have the checkbox and label side-by-side as in your glitch, but also to enable hiding of sub-controls

<details><summary>HTML</summary>

```HTML
<style>
    fieldset {
        border: none;
    }
    
    input {
        display: block;
    }
</style>

<form>

    <fieldset>
        <details>
            <summary>
                <label>
                    <input type="checkbox" checked>
                    <span>Canada Base Map - Transportation (CBMT)</span>
                </label>
            </summary>

            <details>
                <summary>
                    <label for="a">
                        Opacity
                    </label>
                </summary>
                <input id="a" type="range">
            </details>
        </details>
    </fieldset>

    <fieldset>
        <details>
            <summary>
                <label>
                    <input type="checkbox" checked>
                    <span>Territorial Evolution of Canada 1867 - Present</span>
                </label>
            </summary>

            <details>
                <summary>
                    <label for="b">
                        Opacity
                    </label>
                </summary>
                <input id="b" type="range">
            </details>

            <details>
                <summary>
                    <label for="c">
                        Date
                    </label>
                </summary>
                <select id="c">
                    <option>Year</option>
                </select>
            </details>
        </details>
    </fieldset>

</form>
```

</details>

View it [here](https://glittery-promotion-569t2e3f.glitch.me/).

**Comment by prushforth** [comment]
That's it exactly!  I will use this to update the code.

**Comment by prushforth** [comment]
@Malvoz  can you clone [this repo](https://github.com/prushforth/Web-Map-Custom-Element/commit/1e6943ba3e21f76940ced717ded3ba4fd33c4cc7) and see if the result looks good?  It validates, but is it accessible? Thanks!

**Comment by Malvoz** [comment]
Did you intend to remove the `<form>` element? It's valid without `<form>`, I'm mostly wondering because you included it initially, maybe you had a use case for it?

So while the HTML is indeed valid and _should_ be accessible, there are at least 2 issues, of which the latter makes me very anxious:

1. Leaflet event handler is hindering keyboard operability of the layer control (checkbox) and so layers can only be toggled using mouse pointer.

2. The map is completely unreadable by screen readers (I tested using NVDA), Chrome dev tools reports for all children of `<map>`:		
    > Accessibility node not exposed.
    >                 "Ancestor's children are all presentational: map"

    See ARIA reference: https://www.w3.org/TR/wai-aria-1.1/#childrenArePresentational.
    I don't suppose there's a way to force the UA to expose the accessibility node(s), the content model of `<map>` only allows for [transparent content](https://html.spec.whatwg.org/multipage/dom.html#transparent-content-models).

**Comment by prushforth** [comment]
> Did you intend to remove the <form> element? I'm only wondering because you included it initially, it's fine without it.

The `<form>` element was created by Leaflet's L.Control.Layers class, but they switched to a `<section>` element, I believe.  I overrode the L.Control.Layers._addItem method, perhaps ill-advisedly (since the '_' indicates that it is a 'private' method), and that method is called to add layers to the control, which now adds a `<fieldset>` instead of a `<label>`, which I had just ignorantly copied from the original Leaflet element structure, I also believe.  I changed the content of the `<label>` to allow the open/closing behavior from `<details>/<summary>`, so now I'm trying to fix the invalid and inaccessible html I created.

> Leaflet event handler is hindering keyboard operability of the layer control (checkbox) and so layers can only be toggled using mouse pointer.

Could be an event handler I added; in fact it probably is.  I will check it out.

> The map is completely unreadable by screen readers (I tested using NVDA), Chrome dev tools reports for all children of `<map>`

> If there isn't a way to force the UA to expose the accessibility node(s), <map> itself is never going to be backwards compatible as a standardized map viewer.

Yikes.  I will dig into this.  If it can't work, best to change horses asap, I guess.

**Comment by prushforth** [comment]
I guess we can use the `geo-map` element to try to establish what accessibility means for this tool, and then see what issues we encounter when trying to port that to `web-map`, or if that is impossible because of the transparent model of `<map>`. I don't see why it would be, since all the important content in either case is in a shadow root. There is a index-geo-map.html in the main folder that invokes geo-map.  map-areas aren't supported by geo-map, since if the proposed element has a name that's not `<map>`, then `<area>` won't be useful with it anyway.

**Comment by Malvoz** [comment]
> I don't see why it would be, since all the important content in either case is in a shadow root.

Ultimately, the rendered HTML is within `<map>` and as such none of the nodes are exposed in the accessibility tree.

We've come to talk about a few things in this issue; 

1. Invalid HTML (which lead me to discover (2)) - I believe you've fixed the invalid HTML, please PR to update! :)
2. Only elements of the transparent content model is allowed for `<map>`, everything else is hidden from ATs which means `<map>` isn't going to serve as a good basis to build upon. 😢
3. Issue with event handler preventing keyboard operability of the checkbox to control visibility of corresponding layer.

Should we track/discuss (2) and (3) in new issues?

**Comment by Malvoz** [comment]
Regarding my statement:

> If there isn't a way to force the UA to expose the accessibility node(s), `<map>` itself is never going to be backwards compatible as a standardized map viewer.

A standardized map viewer built on `<map>` would of course have to allow exposing the child nodes of `<map>` in the accessibility tree, it would just be a bit awkward to polyfill as you'd need to create a container element and append the map content outside of `<map>`.

**Comment by prushforth** [comment]
> Invalid HTML (which lead me to discover (2)) - I believe you've fixed the invalid HTML, please PR to update!

OK, I need to commit some more things.  I will have to make branches from specific commits  because the commits relate to different things so the changes would seem chaotic otherwise.  Hopefully will get to that soon...
